### ISSUE TITLE
Not Receiving Notifications

### ISSUE THREAD

**Issue by problemss** [python-ring-doorbell/python-ring-doorbell#111]
I see some comments from over a year ago about notifications not working. I am trying now by setting `persist_token=True, push_token_notify_url="http://mysite.com"` when I setup my Ring object. I am not receiving anything on the site I have setup. If this is working, what am I doing wrong? If it is not working, can this be an enhancement request?

For now I will experiment with IFTTT to create the trigger, but they are not responsive. Would much rather get it directly from Ring.

**Comment by tchellomello** [comment]
Hello @problemss, since an update back ago in the Ring servers, the notification stopped to work. That would require more investigation to make it work. Any assistance is very welcome!

**Comment by jsetton** [comment]
Below are the packets from the latest android app using mitmproxy related to the push notification subscription. Both of them got a 204 response with no content. My testing was unsuccessful using my own site url as `push_notification_token` in the request. I am not sure if there is anything we can do at this point.

```
PATCH https://api.ring.com/clients_api/device HTTP/2.0
:authority:		api.ring.com
user-agent:		android:com.ringapp:3.10.1(1)
hardware_id:		<HardwareId>
x-api-lang:		en
authorization:		Bearer <AccessToken>
accept:			application.vnd.api.v11+json
content-type:		application/json; charset=UTF-8
content-length:		637
accept-encoding:	gzip
{
    "device": {
        "metadata": {
            "api_version": "11",
            "app_build": "1",
            "app_instalation_date": "2019-02-13T01:33:18.701Z",
            "app_version": "3.10.1",
            "architecture": "x86",
            "device_model": "Android SDK built for x86",
            "h264": "unknown:52 baseline:52 main:52 unknown:52 high:52 ",
            "is_tablet": false,
            "language": "en",
            "linphone_initialized": false,
            "manufacturer": "Google",
            "os_version": "9 (28)",
            "pn_service": "fcm",
            "resolution": "1440x2712",
            "supports_echo_canceler": false
        },
        "os": "android",
        "push_notification_token": "<FirebaseInstanceIdToken>"
    }
}
```

```
POST https://prd-ring-web-us.prd.rings.solutions/api/v1/rs/notifications/bind?api_version=11 HTTP/2.0
:authority:		prd-ring-web-us.prd.rings.solutions
user-agent:		android:com.ringapp:3.10.1(1)
hardware_id:		<HardwareId>
x-api-lang:		en
authorization:		Bearer <AccessToken>
x-ring-app-version:	Android-3.10.1
content-type:		application/json; charset=UTF-8
content-length:		241
accept-encoding:	gzip
{
    "deviceId": "<HardwareId>",
    "deviceToken": "<FirebaseInstanceIdToken>",
    "platform": "ANDROID"
}
```

**Comment by sdb9696** [comment]
Closing as this is now supported by the library using the `ring-doorbell listen` cli command or via the api with the `RingEventListener`
