### ISSUE TITLE
pyproject include = ["LICENSE", "CONTRIBUTING.rst"...]

### ISSUE THREAD

**Issue by cpina** [python-ring-doorbell/python-ring-doorbell#324]
This is a question.

In the `pyproject.toml` there is:
```
include = [
    "LICENSE",
    "CONTRIBUTING.rst",
    "CHANGELOG.rst",
    "scripts/ringcli.py"
]
```

I haven't done much Python packaging. But for other packages that I've done in Debian: this was never there, and because it's there I need to fix it in the Debian package (else the files go to an unexpected place).

If I install python-ring-doorbell with pip I see:
```
carles@pinux:~/p$ find . -iname "contributing.rst"
./venv/lib/python3.11/site-packages/CONTRIBUTING.rst
carles@pinux:~/p$ 
```

Which does not seem the correct place for CONTRIBUTING.rst (same for the other files).

I suggest to delete the include (I can do a quick PR if needed) to avoid installing those files in `site-packages/` (this is using pip), besides making Debian package more standard. Of course, unless there is a good reason to have the `include = ` there (which I might have missed, only seeing what's happening in other packages).

Also, I don't know the best way to include the files in the pip (I can have a look at other packages...) or if they should be in a subdirectory.

Thanks for considering it!

**Comment by sdb9696** [comment]
This has been resolved for a while now, the wheel no longer contains any extra files.
