### ISSUE TITLE
open door command intercom ring / send rpc command

### ISSUE THREAD

**Issue by cobertgael** [python-ring-doorbell/python-ring-doorbell#383]
Hello
i installed a ring intercom, in order to pilot my interphone, so i can open it remotely
what is the command to open the door ?
thanks for you answer

ring-doorbell raw-query --url  ???

 "supported_rpc_commands": [
there is : unlock_door

how can i send a rpc_command

thanks

**Comment by sdb9696** [comment]
Hi apologies for the delay in coming back. Are you still interested in getting this working?

**Comment by mhuescar** [comment]
I'm very interested in getting this working

**Comment by sdb9696** [comment]
So I don't have an intercom device to test with but I have implemented a cli command in a development branch.  Could you please test it out for me by installing with the following command:

`pip3 install "ring-doorbell[listen] @ git+https://github.com/python-ring-doorbell/python-ring-doorbell.git@feat/cli/open_door"`

Then running `ring-doorbell open-door`.  If you have more than one intercom you'll need to provide the `--device-name` option.

**Comment by mhuescar** [comment]
Thank you so much. It works!

**Comment by sdb9696** [comment]
Great, so I need to add some unit tests then I'll get it merged to master. Will hopefully be in the next few days. Are you running it from master or do you need it to be released?

**Comment by mhuescar** [comment]
I am running it from master, that works for me. Thank you!

**Comment by sdb9696** [comment]
This is now merged to master and also released.
