### ISSUE TITLE
Add support for knock detection

### ISSUE THREAD

**Issue by craigrouse** [python-ring-doorbell/python-ring-doorbell#384]
The Ring peephole/door view cam has a "knock detection" feature that triggers a ding when it detects a door knock. It triggers a type of API event called "door_activity" (lovely, descriptive name ;)), but to all intents and purposes, it is really a ding, and should be treated as such. It's implemented in another library here: https://github.com/dgreif/ring/blob/main/packages/ring-client-api/ring-types.ts. Because this library doesn't expose the door_activity event, any integration depending on it, such as the Home Assistant integration, doesn't get visibility of this event at all.

**Comment by sdb9696** [comment]
Hi there, apologies for the late response as I've had make a bunch of changes to support the new ring event system.  Do you still want this feature? Would you be able to test out the change for me?
