### ISSUE TITLE
Ring Intercom - ding not detected

### ISSUE THREAD

**Issue by Kianda** [python-ring-doorbell/python-ring-doorbell#385]
Hi!

I'm currently testing this library (inside a clean Docker container) with my "Ring Intercom" device:

`docker run -it --rm --name ring-testing ubuntu:jammy`
`apt-get update && apt install -y python3 python3-pip wget git && pip install ring_doorbell[listen]`

`ring-doorbell` (login, works)
`ring-doorbell dings` (not working, it does not give any result if I run the command after I ringed or while the 'ding' is active)
`ring-doorbell history` --device-name "DEVICE_NAME_HERE" (works and shows all the latest dings)
`ring-doorbell listen` (got the notification on my smartphone on the Ring app but nothing on the CLI while listen was active and running)

Any suggestion on how to debug what's wrong? Ring changed some API endpoints? :(

**Comment by sdb9696** [comment]
Hi, could you try with the latest version of the app and let me know if it's now working.  Ring did change some api endpoints but I think the latest version should address this.

**Comment by sdb9696** [comment]
I think this is fixed now so closing
